### ISSUE TITLE
Recv - Not all data was recieved

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw5#23]
Hi,

In my local machine (Windows MinGW), while I was trying to use bin/compare_puzzle_output, it always shows the following error message:

[execute_puzzle], 1479754756.60, 2, Loading reference w/logic_sim.ref.out
Caught exception : FileInStream::Recv - Not all data was recieved

This happens even for completely unchanged puzzles as well.

What could be the possible reasons for having such errors?

Thank you!

Best, awai54st

**Comment by m8pple** [comment]
Interesting, I don't think I've seen that before, it seemed to work
ok when I tested in mingw.

I'm looking at it now.

**Comment by m8pple** [comment]
Hrmm, looks like if you get unlucky one of the bytes is interpreted
as "end of file". Go windows and text-mode files!

**Comment by m8pple** [comment]
I've committed what I think is a fix on the branch "fix-mingw".
Could you check that it fixes the problem for you?

Probably the easiest is to create a fresh repository and try
that:

    git clone https://github.com/HPCE/hpce-2016-cw5.git
    cd hpce-2016-cw5
    git checkout fix-mingw
    make serenity_now -B

If that works, I'll merge it into master.

The fix is essentially just the change here:
https://github.com/HPCE/hpce-2016-cw5/blob/fix-mingw/include/puzzler/core/streams/file_in_stream.hpp#L24-L28

**Comment by awai54st** [comment]
Hi,

I have tested this on my machine and I can confirm that this change has fixed my issue! (At least when *.got.out = *.ref.out, I will still receive this error if my output is wrong but that is to be expected)

Thank you!

Best, awai54st

**Comment by m8pple** [comment]
Thanks, I've merged it in.
